version: "3.9"
services:
  basic-docker-web:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mysql
    links:
      - mysql
    command: npx nodemon index.js

    volumes:
      - ./public/uploads:/usr/src/app/public/uploads

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: linebot@2023$
      MYSQL_DATABASE: my_db_book
    ports:
      - "3306:3306"

    volumes:
      - ./database-data-mysql:/data/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - "8080:80"

    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: linebot@2023$

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/STAR_rmutt_ac_th.crt:/etc/nginx/certs/STAR_rmutt_ac_th.crt
      - ./ssl/rmutt.key:/etc/nginx/certs/rmutt.key
    depends_on:
      - basic-docker-web
      - phpmyadmin
