version: "3.9"
services:
  basic-docker-web:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mysql
    links:
      - mysql
    command: npx nodemon index.js # เปลี่ยนคำสั่งนี้

    volumes:
      - ./public/uploads:/usr/src/app/public/uploads

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - basic-docker-web
      - phpmyadmin
